-- unsaved.vhd

-- Generated using ACDS version 14.1 186 at 2020.01.24.16:25:24

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity unsaved is
	port (
		clk_clk         : in std_logic := '0'; --       clk.clk
		reset_reset_n   : in std_logic := '0'; --     reset.reset_n
		reset_pll_reset : in std_logic := '0'  -- reset_pll.reset
	);
end entity unsaved;

architecture rtl of unsaved is
	component unsaved_usb_pll is
		port (
			clk       : in  std_logic                     := 'X';             -- clk
			reset     : in  std_logic                     := 'X';             -- reset
			read      : in  std_logic                     := 'X';             -- read
			write     : in  std_logic                     := 'X';             -- write
			address   : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			readdata  : out std_logic_vector(31 downto 0);                    -- readdata
			writedata : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			c2        : out std_logic;                                        -- clk
			areset    : in  std_logic                     := 'X';             -- export
			c0        : out std_logic;                                        -- export
			locked    : out std_logic;                                        -- export
			phasedone : out std_logic                                         -- export
		);
	end component unsaved_usb_pll;

begin

	usb_pll : component unsaved_usb_pll
		port map (
			clk       => clk_clk,         --       inclk_interface.clk
			reset     => reset_pll_reset, -- inclk_interface_reset.reset
			read      => open,            --             pll_slave.read
			write     => open,            --                      .write
			address   => open,            --                      .address
			readdata  => open,            --                      .readdata
			writedata => open,            --                      .writedata
			c2        => open,            --                    c2.clk
			areset    => open,            --        areset_conduit.export
			c0        => open,            --            c0_conduit.export
			locked    => open,            --        locked_conduit.export
			phasedone => open             --     phasedone_conduit.export
		);

end architecture rtl; -- of unsaved
